# Generated by Django 2.1 on 2018-08-15 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kinoportal', '0003_auto_20180811_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcard',
            name='thumbnail',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
